services:

  db:
    image: postgres:16.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
