spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/lockdb"
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 5000
  flyway:
    schemas: public

logging:
  level:
    sql: debug